name: Deploy webApp to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml      
          name: webApp-build       
          path: webApp/dist        
          workflow_conclusion: success 
          search_artifacts: true    

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: webApp/dist